from django.urls import path
from . import views

urlpatterns = [
    path('clients/', views.liste_clients, name='liste_clients'),
    path('clients/<int:client_id>/', views.detail_client, name='detail_client'),
    path('clients/creer/', views.creer_client, name='creer_client'),
    path('clients/<int:client_id>/modifier/', views.modifier_client, name='modifier_client'),
    path('clients/<int:client_id>/supprimer/', views.supprimer_client, name='supprimer_client'),
    path('clients/export-pdf/', views.exporter_clients_pdf, name='exporter_clients_pdf'),
    path('clients/<int:client_id>/export-pdf/', views.exporter_client_detail_pdf, name='exporter_client_detail_pdf'),

    path('chauffeurs/', views.liste_chauffeurs, name='liste_chauffeurs'),
    path('chauffeurs/<int:chauffeur_id>/', views.detail_chauffeur, name='detail_chauffeur'),
    path('chauffeurs/creer/', views.creer_chauffeur, name='creer_chauffeur'),
    path('chauffeurs/<int:chauffeur_id>/modifier/', views.modifier_chauffeur, name='modifier_chauffeur'),
    path('chauffeurs/<int:chauffeur_id>/supprimer/', views.supprimer_chauffeur, name='supprimer_chauffeur'),
    path('chauffeurs/<int:chauffeur_id>/modifier-statut/', views.modifier_statut_chauffeur, name='modifier_statut_chauffeur'),
    path('chauffeurs/export-pdf/', views.exporter_chauffeurs_pdf, name='exporter_chauffeurs_pdf'),
    path('chauffeurs/<int:chauffeur_id>/export-pdf/', views.exporter_chauffeur_detail_pdf, name='exporter_chauffeur_detail_pdf'),

    path('vehicules/', views.liste_vehicules, name='liste_vehicules'),
    path('vehicules/<int:vehicule_id>/', views.detail_vehicule, name='detail_vehicule'),
    path('vehicules/creer/', views.creer_vehicule, name='creer_vehicule'),
    path('vehicules/<int:vehicule_id>/modifier/', views.modifier_vehicule, name='modifier_vehicule'),
    path('vehicules/<int:vehicule_id>/supprimer/', views.supprimer_vehicule, name='supprimer_vehicule'),
    path('vehicules/<int:vehicule_id>/modifier-statut/', views.modifier_statut_vehicule, name='modifier_statut_vehicule'),
    path('vehicules/export-pdf/', views.exporter_vehicules_pdf, name='exporter_vehicules_pdf'),
    path('vehicules/<int:vehicule_id>/export-pdf/', views.exporter_vehicule_detail_pdf, name='exporter_vehicule_detail_pdf'),

    path('typeservices/', views.liste_typeservices, name='liste_typeservices'),
    path('typeservices/<int:typeservice_id>/', views.detail_typeservice, name='detail_typeservice'),
    path('typeservices/creer/', views.creer_typeservice, name='creer_typeservice'),
    path('typeservices/<int:typeservice_id>/modifier/', views.modifier_typeservice, name='modifier_typeservice'),
    path('typeservices/<int:typeservice_id>/supprimer/', views.supprimer_typeservice, name='supprimer_typeservice'),
    path('typeservices/export-pdf/', views.exporter_typeservices_pdf, name='exporter_typeservices_pdf'),
    path('typeservices/<int:typeservice_id>/export-pdf/', views.exporter_typeservice_detail_pdf, name='exporter_typeservice_detail_pdf'),

    path('destinations/', views.liste_destinations, name='liste_destinations'),
    path('destinations/<int:destination_id>/', views.detail_destination, name='detail_destination'),
    path('destinations/creer/', views.creer_destination, name='creer_destination'),
    path('destinations/<int:destination_id>/modifier/', views.modifier_destination, name='modifier_destination'),
    path('destinations/<int:destination_id>/supprimer/', views.supprimer_destination, name='supprimer_destination'),
    path('destinations/export-pdf/', views.exporter_destinations_pdf, name='exporter_destinations_pdf'),
    path('destinations/<int:destination_id>/export-pdf/', views.exporter_destination_detail_pdf, name='exporter_destination_detail_pdf'),

    path('tarifications/', views.liste_tarifications, name='liste_tarifications'),
    path('tarifications/<int:tarification_id>/', views.detail_tarification, name='detail_tarification'),
    path('tarifications/creer/', views.creer_tarification, name='creer_tarification'),
    path('tarifications/<int:tarification_id>/modifier/', views.modifier_tarification, name='modifier_tarification'),
    path('tarifications/<int:tarification_id>/supprimer/', views.supprimer_tarification, name='supprimer_tarification'),
    path('tarifications/export-pdf/', views.exporter_tarifications_pdf, name='exporter_tarifications_pdf'),
    path('tarifications/<int:tarification_id>/export-pdf/', views.exporter_tarification_detail_pdf, name='exporter_tarification_detail_pdf'),

    path('tournees/', views.liste_tournees, name='liste_tournees'),
    path('tournees/<int:tournee_id>/', views.detail_tournee, name='detail_tournee'),
    path('tournees/creer/', views.creer_tournee, name='creer_tournee'),
    path('tournees/<int:tournee_id>/modifier/', views.modifier_tournee, name='modifier_tournee'),
    path('tournees/<int:tournee_id>/supprimer/', views.supprimer_tournee, name='supprimer_tournee'),
    path('tournees/<int:tournee_id>/terminer/', views.terminer_tournee, name='terminer_tournee'),
    path('tournees/export-pdf/', views.exporter_tournees_pdf, name='exporter_tournees_pdf'),
    path('tournees/<int:tournee_id>/export-pdf/', views.exporter_tournee_detail_pdf, name='exporter_tournee_detail_pdf'),

    path('expeditions/', views.liste_expeditions, name='liste_expeditions'),
    path('expeditions/<int:expedition_id>/', views.detail_expedition, name='detail_expedition'),
    path('expeditions/creer/', views.creer_expedition, name='creer_expedition'),
    path('expeditions/<int:expedition_id>/modifier/', views.modifier_expedition, name='modifier_expedition'),
    path('expeditions/<int:expedition_id>/supprimer/', views.supprimer_expedition, name='supprimer_expedition'),
    path('expeditions/export-pdf/', views.exporter_expeditions_pdf, name='exporter_expeditions_pdf'),
    path('expeditions/<int:expedition_id>/export-pdf/', views.exporter_expedition_detail_pdf, name='exporter_expedition_detail_pdf'),
    
    path('trackings/', views.liste_trackings, name='liste_trackings'),
    path('trackings/<int:expedition_id>/', views.detail_tracking, name='detail_tracking'),
]