# Generated by Django 4.2.27 on 2025-12-22 12:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='DZ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('wilaya', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_permis', models.CharField(max_length=50, unique=True)),
                ('date_obtention_permis', models.DateField()),
                ('date_expiration_permis', models.DateField()),
                ('categorie_permis', models.CharField(choices=[('B', 'Catégorie B - Véhicules légers'), ('C', 'Catégorie C - Poids lourds'), ('D', 'Catégorie D - Transport de personnes'), ('EC', 'Catégorie EC - Poids lourds avec remorque')], max_length=5)),
                ('date_embauche', models.DateField()),
                ('salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut_disponibilite', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_TOURNEE', 'En tournée'), ('CONGE', 'En congé'), ('MALADIE', 'Maladie'), ('AUTRE', 'Autre raison')], default='DISPONIBLE', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('remarques', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100)),
                ('wilaya', models.CharField(max_length=100)),
                ('pays', models.CharField(default='Algérie', max_length=100)),
                ('zone_geographique', models.CharField(choices=[('LOCALE', 'Locale'), ('NATIONALE', 'Nationale'), ('INTERNATIONALE', 'Internationale')], max_length=20)),
                ('distance_depuis_depot', models.IntegerField(help_text='Distance en km depuis le dépôt principal')),
                ('delai_livraison_jours', models.IntegerField(help_text='Délai de livraison estimé en jours')),
                ('tarif_base', models.DecimalField(decimal_places=2, help_text='Tarif de base pour cette destination', max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('remarques', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_service', models.CharField(choices=[('STANDARD', 'Standard'), ('EXPRESS', 'Express'), ('INTERNATIONAL', 'International')], max_length=20, unique=True)),
                ('multiplicateur_prix', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplicateur du prix (1.00 = normal, 2.00 = x2 plus cher)', max_digits=5)),
                ('multiplicateur_delai', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplicateur du délai (0.50 = 2x plus rapide, 1.00 = normal)', max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_immatriculation', models.CharField(max_length=50, unique=True)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('type_vehicule', models.CharField(choices=[('CAMIONNETTE', 'Camionnette'), ('CAMION', 'Camion'), ('FOURGON', 'Fourgon'), ('MOTO', 'Moto')], max_length=20)),
                ('capacite_poids', models.DecimalField(decimal_places=2, help_text='Capacité en kg', max_digits=8)),
                ('capacite_volume', models.DecimalField(decimal_places=2, help_text='Volume en m³', max_digits=8)),
                ('consommation_moyenne', models.DecimalField(decimal_places=2, help_text='Consommation en L/100km', max_digits=5)),
                ('etat', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('BON', 'Bon'), ('MOYEN', 'Moyen'), ('MAUVAIS', 'Mauvais'), ('EN_REPARATION', 'En réparation')], default='BON', max_length=20)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_TOURNEE', 'En tournée'), ('EN_MAINTENANCE', 'En maintenance'), ('HORS_SERVICE', 'Hors service')], default='DISPONIBLE', max_length=20)),
                ('date_derniere_revision', models.DateField(blank=True, null=True)),
                ('date_prochaine_revision', models.DateField(blank=True, null=True)),
                ('kilometrage', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_acquisition', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('remarques', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='remarques',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='client',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+213000000000', max_length=128, region='DZ', unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif_poids', models.DecimalField(decimal_places=2, help_text='Tarif par kg en DA', max_digits=10)),
                ('tarif_volume', models.DecimalField(decimal_places=2, help_text='Tarif par m³ en DA', max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.destination')),
                ('type_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.typeservice')),
            ],
        ),
    ]
