# Generated by Django 4.2.27 on 2025-12-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_chauffeur_destination_typeservice_vehicule_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='distance_depuis_depot',
            new_name='distance_estimee',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='delai_livraison_jours',
        ),
        migrations.AddField(
            model_name='client',
            name='date_naissance',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='destination',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='delai_livraison_estime',
            field=models.IntegerField(blank=True, help_text='Délai estimé en jours', null=True),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_naissance',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='tarif_base',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Tarif de base en DA (calculé : distance × 50)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='destination',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='zone_geographique',
            field=models.CharField(choices=[('LOCALE', 'Locale (même wilaya)'), ('NATIONALE', 'Nationale'), ('INTERNATIONALE', 'Internationale')], max_length=20),
        ),
    ]
