# Generated by Django 4.2.27 on 2026-01-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_chauffeur_cree_par_chauffeur_modifie_par_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_TRANSIT', 'En transit'), ('LIVRE', 'Livré'), ('ECHEC', 'Échec'), ('REENVOYE', 'Réexpédié')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='trackingexpedition',
            name='statut_etape',
            field=models.CharField(choices=[('COLIS_CREE', 'Colis créé'), ('EN_ATTENTE', 'En attente'), ('EN_TRANSIT', 'En transit'), ('LIVRE', 'Livré'), ('ECHEC', 'Échec'), ('INCIDENT', 'Incident signalé'), ('INCIDENT_RESOLU', 'Incident résolu'), ('ANNULE', 'Annulé'), ('REENVOYE', 'Réexpédié')], max_length=20),
        ),
    ]
