# Generated by Django 4.2.27 on 2026-01-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_expedition_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('MAINTENANCE_AVANT', 'Maintenance prévue demain'), ('MAINTENANCE_APRES', 'Véhicule en maintenance - Retour?'), ('SOLDE_NEGATIF', 'Client en crédit'), ('REMBOURSEMENT_REQUIS', 'Remboursement incident requis'), ('TOURNEE_TERMINEE', 'Tournée terminée'), ('INFO', 'Information'), ('ALERTE', 'Alerte'), ('INCIDENT_CREE', 'Nouvel incident créé'), ('INCIDENT_AFFECTE', 'Incident affecté'), ('RECLAMATION_CREEE', 'Réclamation créée'), ('RECLAMATION_AFFECTEE', 'Réclamation affectée'), ('INCIDENT_RESOLU', 'Incident résolu'), ('RECLAMATION_RESOLUE', 'Réclamation résolue')], max_length=30),
        ),
    ]
