# Generated by Django 4.2.27 on 2025-12-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_distance_depuis_depot_destination_distance_estimee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='delai_livraison_estime',
            field=models.IntegerField(default=1, editable=False, help_text='Délai estimé en jours (calculé : 1 jour par 30 km)'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='tarif_base',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Tarif de base en DA (calculé : distance × 50)', max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='tarification',
            unique_together={('type_service', 'destination')},
        ),
    ]
