# Generated by Django 4.2.27 on 2025-12-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_destination_delai_livraison_estime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeservice',
            name='multiplicateur_delai',
            field=models.DecimalField(decimal_places=2, default=1.0, editable=False, help_text='Multiplicateur du délai (0.50 = 2x plus rapide, 1.00 = normal)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='multiplicateur_prix',
            field=models.DecimalField(decimal_places=2, default=1.0, editable=False, help_text='Multiplicateur du prix (1.00 = normal, 2.00 = x2 plus cher)', max_digits=5),
        ),
    ]
