# Generated by Django 4.2.27 on 2026-01-13 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_notification_type_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reclamation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app1.reclamation'),
        ),
    ]
