# Generated by Django 4.2.27 on 2026-01-13 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_notification_reclamation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='signale_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_signales', to=settings.AUTH_USER_MODEL, verbose_name='Signalé par (agent)'),
        ),
    ]
