# Generated by Django 4.2.27 on 2025-12-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_typeservice_multiplicateur_delai_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tarification',
            unique_together={('destination', 'type_service')},
        ),
        migrations.AlterField(
            model_name='destination',
            name='tarif_base',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Tarif de base en DA (calculé : distance × 20)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tarification',
            name='tarif_poids',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Tarif par kg en DA', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tarification',
            name='tarif_volume',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Tarif par m³ en DA', max_digits=10),
        ),
        migrations.RemoveField(
            model_name='tarification',
            name='remarques',
        ),
    ]
