# Generated by Django 4.2.27 on 2025-12-22 21:17

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_tarification_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_destinataire', models.TextField(help_text='Adresse complète de livraison')),
                ('nom_destinataire', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone_destinataire', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='DZ')),
                ('poids', models.DecimalField(decimal_places=2, help_text='Poids en kg', max_digits=8)),
                ('volume', models.DecimalField(decimal_places=2, help_text='Volume en m³', max_digits=8)),
                ('description', models.TextField(blank=True, help_text='Description du contenu', null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Montant calculé automatiquement', max_digits=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_TRANSIT', 'En transit'), ('EN_CENTRE_TRI', 'En centre de tri'), ('EN_LIVRAISON', 'En cours de livraison'), ('LIVRE', 'Livré'), ('ECHEC', 'Échec de livraison')], default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_livraison_prevue', models.DateField(blank=True, editable=False, help_text='Date calculée automatiquement selon le délai', null=True)),
                ('date_livraison_reelle', models.DateField(blank=True, null=True)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.client')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.destination')),
                ('type_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.typeservice')),
            ],
        ),
    ]
