# Generated by Django 4.2.27 on 2025-12-22 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_expedition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedition',
            name='date_livraison_reelle',
        ),
    ]
