# Generated by Django 4.2.27 on 2025-12-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_expedition_date_livraison_reelle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedition',
            name='remarques',
        ),
        migrations.AlterField(
            model_name='tarification',
            name='tarif_poids',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tarification',
            name='tarif_volume',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
    ]
