# Generated by Django 4.2.27 on 2025-12-22 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_expedition_remarques_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='zone_logistique',
            field=models.CharField(choices=[('CENTRE', 'Centre (Alger, Blida...)'), ('EST', 'Est (Constantine, Annaba, Sétif...)'), ('OUEST', 'Ouest (Oran, Tlemcen, Sidi Bel Abbès...)'), ('SUD', 'Sud (Tamanrasset, Adrar, Bechar...)')], default='CENTRE', help_text='Utilisé pour regrouper les expéditions dans une même tournée', max_length=10),
        ),
        migrations.AddField(
            model_name='expedition',
            name='date_livraison_reelle',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateTimeField()),
                ('zone_cible', models.CharField(choices=[('CENTRE', 'Centre (Alger, Blida...)'), ('EST', 'Est (Constantine, Annaba, Sétif...)'), ('OUEST', 'Ouest (Oran, Tlemcen, Sidi Bel Abbès...)'), ('SUD', 'Sud (Tamanrasset, Adrar, Bechar...)')], max_length=10)),
                ('kilometrage_depart', models.PositiveIntegerField(help_text='Rempli automatiquement au départ')),
                ('kilometrage_arrivee', models.PositiveIntegerField(blank=True, help_text='À saisir au retour du chauffeur', null=True)),
                ('consommation_carburant', models.DecimalField(blank=True, decimal_places=2, help_text='En litres', max_digits=6, null=True)),
                ('statut', models.CharField(choices=[('PREVUE', 'Prévue'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée')], default='PREVUE', max_length=20)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.chauffeur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.vehicule')),
            ],
        ),
        migrations.AddField(
            model_name='expedition',
            name='tournee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='app1.tournee'),
        ),
    ]
