# Generated by Django 4.2.27 on 2025-12-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_destination_zone_logistique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedition',
            name='date_modification',
        ),
        migrations.AlterField(
            model_name='expedition',
            name='date_livraison_prevue',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='poids',
            field=models.DecimalField(decimal_places=2, help_text='kg', max_digits=8),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_TRANSIT', 'En transit'), ('LIVRE', 'Livré'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='volume',
            field=models.DecimalField(decimal_places=2, help_text='m³', max_digits=8),
        ),
        migrations.AlterField(
            model_name='tournee',
            name='kilometrage_arrivee',
            field=models.PositiveIntegerField(blank=True, help_text='À saisir au retour', null=True),
        ),
        migrations.AlterField(
            model_name='tournee',
            name='kilometrage_depart',
            field=models.PositiveIntegerField(help_text='Auto-rempli depuis le véhicule au départ'),
        ),
    ]
