# Generated by Django 4.2.27 on 2025-12-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_expedition_date_modification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='kilometrage',
        ),
        migrations.AddField(
            model_name='vehicule',
            name='kilometrage_depart',
            field=models.PositiveIntegerField(blank=True, help_text='Laissé vide, il sera rempli automatiquement par le compteur du véhicule', null=True),
        ),
    ]
