# Generated by Django 4.2.27 on 2025-12-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_vehicule_kilometrage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournee',
            name='kilometrage_depart',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-rempli depuis le véhicule au départ', null=True),
        ),
    ]
