# Generated by Django 4.2.27 on 2025-12-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_tournee_kilometrage_depart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='kilometrage_depart',
        ),
        migrations.AddField(
            model_name='vehicule',
            name='kilometrage',
            field=models.PositiveIntegerField(default=0, help_text='Compteur kilométrique total du véhicule'),
        ),
    ]
