# Generated by Django 4.2.27 on 2025-12-23 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_remove_vehicule_kilometrage_depart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournee',
            name='date_retour_prevue',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TrackingExpedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_evenement', models.DateTimeField(auto_now_add=True)),
                ('statut_etape', models.CharField(choices=[('COLIS_CREE', 'Colis enregistré'), ('AFFECTE_TOURNEE', 'Affecté à une tournée'), ('EN_CHARGEMENT', 'En cours de chargement (2h avant départ)'), ('EN_TRANSIT', 'En transit (Camion en route)'), ('LIVRE', 'Livré à destination'), ('ECHEC_LIVRAISON', 'Échec de livraison (Incident)'), ('RETOUR_DEPOT', 'Retour au dépôt')], max_length=30)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_tracking', to='app1.expedition')),
            ],
            options={
                'ordering': ['-date_evenement'],
            },
        ),
    ]
