# Generated by Django 4.2.27 on 2025-12-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_tournee_date_retour_prevue_trackingexpedition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingexpedition',
            name='statut_etape',
            field=models.CharField(blank=True, choices=[('COLIS_CREE', 'Colis enregistré'), ('AFFECTE_TOURNEE', 'Affecté à une tournée'), ('EN_CHARGEMENT', 'En cours de chargement (2h avant départ)'), ('EN_TRANSIT', 'En transit (Camion en route)'), ('LIVRE', 'Livré à destination'), ('ECHEC_LIVRAISON', 'Échec de livraison (Incident)'), ('RETOUR_DEPOT', 'Retour au dépôt')], max_length=30),
        ),
    ]
