# Generated by Django 4.2.27 on 2025-12-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_trackingexpedition_statut_etape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chauffeur',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='chauffeur',
            name='categorie_permis',
        ),
        migrations.RemoveField(
            model_name='client',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='tarification',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='typeservice',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='typeservice',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='typeservice',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='typeservice',
            name='multiplicateur_delai',
        ),
        migrations.RemoveField(
            model_name='typeservice',
            name='multiplicateur_prix',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='actif',
        ),
        migrations.AlterField(
            model_name='destination',
            name='delai_livraison_estime',
            field=models.IntegerField(default=1, help_text='Délai estimé en jours'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='tarif_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tarif de base en DA', max_digits=10),
        ),
        migrations.AlterField(
            model_name='destination',
            name='zone_logistique',
            field=models.CharField(choices=[('CENTRE', 'Centre (Alger, Blida...)'), ('EST', 'Est (Constantine, Annaba, Sétif...)'), ('OUEST', 'Ouest (Oran, Tlemcen, Sidi Bel Abbès...)'), ('SUD', 'Sud (Tamanrasset, Adrar, Bechar...)')], default='CENTRE', max_length=10),
        ),
        migrations.AlterField(
            model_name='tarification',
            name='tarif_poids',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Tarif par kg en DA', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tarification',
            name='tarif_volume',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Tarif par m³ en DA', max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='etat',
            field=models.CharField(choices=[('EXCELLENT', 'Excellent'), ('BON', 'Bon'), ('MOYEN', 'Moyen'), ('MAUVAIS', 'Mauvais')], default='BON', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='kilometrage',
            field=models.PositiveIntegerField(default=0, help_text='Compteur kilométrique total'),
        ),
    ]
