# Generated by Django 4.2.27 on 2025-12-25 17:39

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_remove_chauffeur_actif_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarification',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='tarification',
            name='date_modification',
        ),
        migrations.AddField(
            model_name='expedition',
            name='email_destinataire',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expedition',
            name='remarques',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournee',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 25, 17, 38, 6, 532382, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournee',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tournee',
            name='date_retour_reelle',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournee',
            name='kilometrage_parcouru',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tournee',
            name='remarques',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='adresse_destinataire',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='date_livraison_reelle',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='nom_destinataire',
            field=models.CharField(default='Destinataire inconnu', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expedition',
            name='poids',
            field=models.DecimalField(decimal_places=2, help_text='Poids en kg', max_digits=8),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='telephone_destinataire',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+213555000000', max_length=128, region='DZ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expedition',
            name='volume',
            field=models.DecimalField(decimal_places=2, help_text='Volume en m³', max_digits=8),
        ),
        migrations.AlterField(
            model_name='tournee',
            name='consommation_carburant',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tournee',
            name='kilometrage_arrivee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournee',
            name='kilometrage_depart',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tournee',
            name='zone_cible',
            field=models.CharField(choices=[('CENTRE', 'Centre'), ('EST', 'Est'), ('OUEST', 'Ouest'), ('SUD', 'Sud')], max_length=10),
        ),
        migrations.DeleteModel(
            name='TrackingExpedition',
        ),
    ]
