# Generated by Django 4.2.27 on 2025-12-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_remove_tarification_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='wilaya',
            field=models.CharField(default='Non spécifiée', max_length=100),
            preserve_default=False,
        ),
    ]
