# Generated by Django 4.2.27 on 2025-12-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_destination_ville_alter_destination_wilaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournee',
            name='est_privee',
            field=models.BooleanField(default=False, help_text='Tournée privée EXPRESS'),
        ),
    ]
