# Generated by Django 4.2.27 on 2025-12-26 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_tournee_est_privee'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingExpedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_etape', models.CharField(choices=[('COLIS_CREE', 'Colis créé'), ('EN_ATTENTE', 'En attente'), ('EN_TRANSIT', 'En transit'), ('LIVRE', 'Livré'), ('ECHEC', 'Échec')], max_length=20)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='app1.expedition')),
            ],
            options={
                'ordering': ['-date_heure'],
            },
        ),
    ]
