# Generated by Django 4.2.27 on 2025-12-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_trackingexpedition'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueExpedition',
            fields=[
            ],
            options={
                'verbose_name': 'Historique expédition',
                'verbose_name_plural': 'Historique expéditions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app1.expedition',),
        ),
    ]
