# Generated by Django 4.2.27 on 2025-12-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_historiqueexpedition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoriqueExpedition',
        ),
    ]
