# Generated by Django 4.2.27 on 2025-12-28 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_delete_historiqueexpedition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(blank=True, max_length=50, unique=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=19.0, max_digits=5)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_echeance', models.DateField()),
                ('statut', models.CharField(choices=[('IMPAYEE', 'Impayée'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée'), ('PAYEE', 'Payée'), ('EN_RETARD', 'En retard'), ('ANNULEE', 'Annulée')], default='IMPAYEE', max_length=20)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='app1.client')),
                ('expeditions', models.ManyToManyField(related_name='factures', to='app1.expedition')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE', 'Carte bancaire'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque')], max_length=20)),
                ('reference_transaction', models.CharField(blank=True, max_length=100, null=True)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(default='VALIDE', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='app1.client')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='app1.facture')),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
    ]
