# Generated by Django 6.0 on 2025-12-29 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_facture_paiement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='expeditions',
        ),
        migrations.AddField(
            model_name='expedition',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='app1.facture'),
        ),
    ]
