# Generated by Django 4.2.27 on 2025-12-31 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_facture_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('MAINTENANCE_AVANT', 'Maintenance prévue demain'), ('MAINTENANCE_APRES', 'Véhicule en maintenance - Retour?'), ('INFO', 'Information'), ('ALERTE', 'Alerte')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('NON_LUE', 'Non lue'), ('LUE', 'Lue'), ('TRAITEE', 'Traitée')], default='NON_LUE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.chauffeur')),
                ('tournee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.tournee')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.vehicule')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
