# Generated by Django 6.0 on 2025-12-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_remove_facture_expeditions_expedition_facture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedition',
            name='facture',
        ),
        migrations.AddField(
            model_name='facture',
            name='expeditions',
            field=models.ManyToManyField(related_name='factures', to='app1.expedition'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=19.0, editable=False, max_digits=5),
        ),
    ]
