# Generated by Django 4.2.27 on 2026-01-03 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_alter_notification_type_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='compensation_autorisee',
            field=models.BooleanField(default=True, help_text='Autoriser la compensation automatique du crédit sur les factures'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_effectuee',
            field=models.CharField(blank=True, help_text="Action effectuée par l'agent (ex: COMPENSATION_AUTORISEE, REMBOURSE, REVISION_CONFIRMEE)", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.client'),
        ),
        migrations.AddField(
            model_name='notification',
            name='commentaire_traitement',
            field=models.TextField(blank=True, help_text="Commentaire de l'agent lors du traitement", null=True),
        ),
    ]
