# Generated by Django 4.2.27 on 2026-01-05 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_client_compensation_autorisee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reclamation', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('type_reclamation', models.CharField(choices=[('EXPEDITION', 'Liée à une expédition'), ('FACTURE', 'Liée à une facture'), ('SERVICE', 'Liée à un service'), ('AUTRE', 'Autre')], default='EXPEDITION', help_text='Type de réclamation', max_length=20)),
                ('service_concerne', models.CharField(blank=True, choices=[('LIVRAISON', 'Service de livraison'), ('FACTURATION', 'Service facturation'), ('CLIENT', 'Service client'), ('TECHNIQUE', 'Service technique'), ('COMMERCIAL', 'Service commercial'), ('AUTRE', 'Autre')], help_text='Service concerné (si type = SERVICE)', max_length=50, null=True)),
                ('nature', models.CharField(choices=[('RETARD_LIVRAISON', 'Retard de livraison'), ('COLIS_ENDOMMAGE', 'Colis endommagé'), ('COLIS_PERDU', 'Colis perdu'), ('ERREUR_FACTURATION', 'Erreur de facturation'), ('MAUVAIS_SERVICE', 'Mauvais service'), ('COMPORTEMENT_CHAUFFEUR', 'Comportement du chauffeur'), ('COLIS_INCOMPLET', 'Colis incomplet'), ('REMBOURSEMENT', 'Demande de remboursement'), ('AUTRE', 'Autre')], max_length=30)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=20)),
                ('objet', models.CharField(help_text='Objet de la réclamation', max_length=200)),
                ('description', models.TextField(help_text='Description détaillée de la réclamation')),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('EN_COURS', 'En cours de traitement'), ('EN_ATTENTE_CLIENT', 'En attente de réponse du client'), ('RESOLUE', 'Résolue'), ('CLOSE', 'Clôturée'), ('ANNULEE', 'Annulée')], default='OUVERTE', max_length=30)),
                ('agent_responsable', models.CharField(blank=True, help_text='Agent assigné', max_length=100, null=True)),
                ('date_assignation', models.DateTimeField(blank=True, null=True)),
                ('reponse_agent', models.TextField(blank=True, help_text="Réponse de l'agent", null=True)),
                ('solution_proposee', models.TextField(blank=True, null=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('delai_traitement_jours', models.IntegerField(blank=True, editable=False, help_text='Calculé automatiquement', null=True)),
                ('commentaire_client', models.TextField(blank=True, null=True)),
                ('piece_jointe1', models.FileField(blank=True, null=True, upload_to='reclamations/documents/')),
                ('piece_jointe2', models.FileField(blank=True, null=True, upload_to='reclamations/documents/')),
                ('compensation_accordee', models.BooleanField(default=False)),
                ('montant_compensation', models.DecimalField(decimal_places=2, default=0, help_text='Montant en DA', max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='app1.client')),
                ('expeditions', models.ManyToManyField(blank=True, help_text='Expéditions concernées', related_name='reclamations', to='app1.expedition')),
                ('facture', models.ForeignKey(blank=True, help_text='Facture concernée (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='app1.facture')),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_incident', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('type_incident', models.CharField(choices=[('RETARD', 'Retard de livraison'), ('PERTE', 'Perte de colis'), ('ENDOMMAGEMENT', 'Endommagement'), ('PROBLEME_TECHNIQUE', 'Problème technique véhicule'), ('ACCIDENT', 'Accident'), ('REFUS_DESTINATAIRE', 'Refus du destinataire'), ('ADRESSE_INCORRECTE', 'Adresse incorrecte'), ('DESTINATAIRE_ABSENT', 'Destinataire absent'), ('AUTRE', 'Autre')], max_length=30)),
                ('severite', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('ELEVEE', 'Élevée'), ('CRITIQUE', 'Critique')], default='MOYENNE', max_length=20)),
                ('titre', models.CharField(help_text="Résumé court de l'incident", max_length=200)),
                ('description', models.TextField(help_text="Description détaillée de l'incident")),
                ('lieu_incident', models.CharField(blank=True, max_length=200, null=True)),
                ('date_heure_incident', models.DateTimeField(help_text="Date et heure de survenue de l'incident")),
                ('statut', models.CharField(choices=[('SIGNALE', 'Signalé'), ('EN_COURS', 'En cours de traitement'), ('RESOLU', 'Résolu'), ('CLOS', 'Clôturé')], default='SIGNALE', max_length=20)),
                ('signale_par', models.CharField(help_text='Nom de la personne ayant signalé', max_length=100)),
                ('agent_responsable', models.CharField(blank=True, help_text='Agent en charge du traitement', max_length=100, null=True)),
                ('actions_entreprises', models.TextField(blank=True, help_text="Actions effectuées pour résoudre l'incident", null=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('cout_estime', models.DecimalField(decimal_places=2, default=0, help_text='Coût estimé en DA', max_digits=10)),
                ('document1', models.FileField(blank=True, null=True, upload_to='incidents/documents/')),
                ('document2', models.FileField(blank=True, null=True, upload_to='incidents/documents/')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='incidents/photos/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='incidents/photos/')),
                ('alerte_direction', models.BooleanField(default=False, help_text='Alerter la direction')),
                ('alerte_client', models.BooleanField(default=False, help_text='Alerter le client')),
                ('remboursement_effectue', models.BooleanField(default=False, help_text='Remboursement effectué au client')),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=0, help_text='Montant remboursé en DA', max_digits=10)),
                ('taux_remboursement', models.DecimalField(decimal_places=2, default=100.0, help_text='Pourcentage de remboursement (0-100%)', max_digits=5)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('expedition', models.ForeignKey(blank=True, help_text='Expédition concernée (si applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='app1.expedition')),
                ('tournee', models.ForeignKey(blank=True, help_text='Tournée concernée (si applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='app1.tournee')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-date_heure_incident'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueReclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(help_text="Type d'action effectuée", max_length=100)),
                ('auteur', models.CharField(help_text="Qui a effectué l'action", max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('ancien_statut', models.CharField(blank=True, max_length=30, null=True)),
                ('nouveau_statut', models.CharField(blank=True, max_length=30, null=True)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='app1.reclamation')),
            ],
            options={
                'verbose_name': 'Historique de réclamation',
                'verbose_name_plural': 'Historiques de réclamations',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(help_text="Type d'action effectuée", max_length=100)),
                ('auteur', models.CharField(help_text="Qui a effectué l'action", max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('ancien_statut', models.CharField(blank=True, max_length=20, null=True)),
                ('nouveau_statut', models.CharField(blank=True, max_length=20, null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='app1.incident')),
            ],
            options={
                'verbose_name': "Historique d'incident",
                'verbose_name_plural': "Historiques d'incidents",
                'ordering': ['-date_action'],
            },
        ),
    ]
