# Generated by Django 4.2.27 on 2026-01-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_reclamation_incident_historiquereclamation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('MAINTENANCE_AVANT', 'Maintenance prévue demain'), ('MAINTENANCE_APRES', 'Véhicule en maintenance - Retour?'), ('SOLDE_NEGATIF', 'Client en crédit'), ('REMBOURSEMENT_REQUIS', 'Remboursement incident requis'), ('INFO', 'Information'), ('ALERTE', 'Alerte')], max_length=30),
        ),
    ]
