# Generated by Django 6.0 on 2026-01-04 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_remove_reclamation_evaluation_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='montant_rembourse',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant remboursé en DA', max_digits=10),
        ),
        migrations.AddField(
            model_name='incident',
            name='remboursement_effectue',
            field=models.BooleanField(default=False, help_text='Remboursement effectué au client'),
        ),
        migrations.AddField(
            model_name='incident',
            name='taux_remboursement',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Pourcentage de remboursement (0-100%)', max_digits=5),
        ),
        migrations.CreateModel(
            name='HistoriqueIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(help_text="Type d'action effectuée", max_length=100)),
                ('auteur', models.CharField(help_text="Qui a effectué l'action", max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('ancien_statut', models.CharField(blank=True, max_length=20, null=True)),
                ('nouveau_statut', models.CharField(blank=True, max_length=20, null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='app1.incident')),
            ],
            options={
                'verbose_name': "Historique d'incident",
                'verbose_name_plural': "Historiques d'incidents",
                'ordering': ['-date_action'],
            },
        ),
    ]
